spring:
  datasource:
    url: jdbc:postgresql://localhost:54311/aoalocaldb
    username: postgres
    password: JRaspberry1!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: aoalocal
        format_sql: true
        show_sql: true
logging:
  level:
    com: debug